version: "3"

services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: distri
      POSTGRES_DB: distri
      POSTGRES_PASSWORD: distri
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

  spring-boot:
    build: ./java
    ports:
      - 8090:8090
    depends_on:
      - postgres
    volumes:
      - ./java:/home/app
    restart: unless-stopped
