version: "3.6"

services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: distri
      POSTGRES_DB: distri
      POSTGRES_PASSWORD: distri
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  spring-boot:
    build: ./java
    ports:
      - 8090:8090
    depends_on:
      - postgres
    volumes:
      - ./java:/home/app
