version: "3"

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: distri
      POSTGRES_DB: distri
      POSTGRES_PASSWORD: distri
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  spring-boot:
    build: ./java
    ports:
      - 8090:8090
    depends_on:
      - postgres
    volumes:
      - ./java:/home/app
