version: '3'

services:

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: distri
      POSTGRES_DB: distri
      POSTGRES_PASSWORD: distri
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

  spring:
    build:
      ./java 
    depends_on:
      - postgres

