version: "3"

services:
  db-pos:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: distri
      POSTGRES_DB: distri
      POSTGRES_PASSWORD: distri
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
  jard:
    build: ./java
    ports:
      - 8091:8090
    depends_on:
      - db-pos
    volumes:
      - ./java:/home/app
